title: haesongkk
url: "https://haesongkk.github.io"
baseurl: ""
timezone: "Asia/Seoul"

markdown: kramdown

theme: minima

collections:
  study:
    output: true
    permalink: /:collection/:path/
  project:
    output: true
    permalink: /:collection/:path/
  codingtest:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope: { type: "study" }
    values: { layout: default }
#   - scope: { type: "project" }
#     values: { layout: item }  
#   - scope: { type: "codingtest" }
#     values: { layout: item }


plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num"